# Generated by Django 4.1.13 on 2024-03-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
