# Generated by Django 4.1.13 on 2024-03-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('education', 'Education'), ('jobs', 'Jobs'), ('career', 'Career goals'), ('skills', 'Skills')], default='personal', max_length=50),
        ),
    ]
