# Generated by Django 4.1.13 on 2024-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_description_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
