# Generated by Django 4.1.13 on 2024-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_description_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, upload_to='description/images/'),
        ),
    ]
